/*---------------------------------------------------------------------------------------------
 * Copyright (c) Lumovy Technology Solutions. All rights reserved.
 *--------------------------------------------------------------------------------------------*/

import { createGetRoute } from "@/lib/api/route";
import { GetChannels } from "./GetChannels";

// Generated plumbing. You normally do not edit this file.
export const GET = createGetRoute(GetChannels);
