/*---------------------------------------------------------------------------------------------
 * Copyright (c) Lumovy Technology Solutions. All rights reserved.
 *--------------------------------------------------------------------------------------------*/

import Link from "next/link";
import type { HeaderProps } from "./header.props.autogenerated";

export function HeaderView({ config, resources, slots }: HeaderProps) {
  return (
    <header
      className={`${config.sticky ? "sticky top-0" : "relative"} z-50 border-b border-black/10 bg-white/95 text-zinc-950 shadow-sm backdrop-blur ${config.className}`}
      style={{
        backgroundColor: config.backgroundColor,
        color: config.foregroundColor,
      }}
    >
      <div
        className={`site-shell flex min-h-20 items-center gap-8 ${config.variant === "centered" ? "flex-col justify-center py-4" : "justify-between"}`}
      >
        <Link href="/" className="shrink-0 text-xl font-bold tracking-tight">
          {resources.siteName}
        </Link>
        <div className="min-w-0 flex-1">{slots.navigation}</div>
      </div>
    </header>
  );
}
