import type { HeaderProps } from "./header.props.autogenerated";
import { getHeaderData } from "./header.data";
import { HeaderView } from "./header.view";

export default async function HeaderModule(props: HeaderProps) {
  const mode = props.config.menuMode === "retail" || props.config.menuMode === "authored" ? props.config.menuMode : "all";
  const data = props.config.menuDataExecution === "client" ? null : await getHeaderData(mode, props.config.wordpressMenuSlug);
  return <HeaderView {...props} data={data} />;
}
