"use client";

import Image from "next/image";
import Link from "next/link";
import { useEffect, useState } from "react";
import type { MenuItem } from "@/lib/demo-menu";
import type { HeaderData } from "./header.data";
import type { HeaderProps } from "./header.props.autogenerated";
import styles from "./header.module.scss";

function MenuBranch({ item, depth = 0, onNavigate }: { item: MenuItem; depth?: number; onNavigate: () => void }) {
  if (!item.children?.length) return <Link href={item.href} onClick={onNavigate}>{item.label}</Link>;
  return (
    <details className={styles.branch}>
      <summary>{item.label}<span aria-hidden="true">⌄</span></summary>
      <ul className={depth === 0 ? styles.dropdown : styles.nested}>
        {item.children.map((child) => <li key={child.id}><MenuBranch item={child} depth={depth + 1} onNavigate={onNavigate} /></li>)}
      </ul>
    </details>
  );
}

function MegaMenu({ item, onNavigate }: { item: MenuItem; onNavigate: () => void }) {
  const featured = item.children?.flatMap((group) => group.children ?? []).filter((child) => child.featured && child.image) ?? [];
  const [active, setActive] = useState(featured[0]);
  return (
    <details className={`${styles.branch} ${styles.megaBranch}`}>
      <summary>{item.label}<span aria-hidden="true">⌄</span></summary>
      <div className={styles.mega}>
        <div className={styles.megaColumns}>
          {item.children?.map((group) => (
            <section key={group.id}>
              <Link className={styles.groupTitle} href={group.href} onClick={onNavigate}>{group.label}</Link>
              <ul>{group.children?.map((child) => <li key={child.id} onMouseEnter={() => child.image && setActive(child)} onFocus={() => child.image && setActive(child)}><MenuBranch item={child} depth={1} onNavigate={onNavigate} /></li>)}</ul>
            </section>
          ))}
        </div>
        {active?.image ? <Link href={active.href} className={styles.feature} onClick={onNavigate}>
          <span className={styles.featureImage}><Image src={active.image} alt="" fill sizes="320px" /></span>
          <strong>{active.label}</strong><span>{active.description}</span>
        </Link> : null}
      </div>
    </details>
  );
}

export function HeaderView({ id, config, resources, data }: HeaderProps & { data: HeaderData | null }) {
  const [clientData, setClientData] = useState<HeaderData | null>(data);
  const [mobileOpen, setMobileOpen] = useState(false);
  const mode = config.menuMode === "retail" || config.menuMode === "authored" ? config.menuMode : "all";

  useEffect(() => {
    if (config.menuDataExecution !== "client") return;
    const controller = new AbortController();
    const query = new URLSearchParams({ mode, menuSlug: config.wordpressMenuSlug || "primary" });
    fetch(`/api/demo/menu?${query}`, { signal: controller.signal })
      .then((response) => { if (!response.ok) throw new Error(`Menu request failed: ${response.status}`); return response.json(); })
      .then((payload: HeaderData) => setClientData(payload))
      .catch((error: unknown) => { if (!(error instanceof DOMException && error.name === "AbortError")) console.error(error); });
    return () => controller.abort();
  }, [config.menuDataExecution, config.wordpressMenuSlug, data, mode]);

  const close = () => setMobileOpen(false);
  const resolvedData = config.menuDataExecution === "client" ? clientData : data;
  return <header className={`${styles.root} ${config.sticky ? styles.sticky : ""}`} style={{ backgroundColor: config.backgroundColor, color: config.foregroundColor }}>
    <div className={`site-shell ${styles.shell} ${config.variant === "centered" ? styles.centered : ""}`}>
      <Link href="/" className={styles.logo} onClick={close}>Dynamics Commerce</Link>
      <button className={styles.mobileToggle} type="button" aria-expanded={mobileOpen} aria-controls={`${id}-navigation`} aria-label={mobileOpen ? resources.closeMenuLabel : resources.openMenuLabel} onClick={() => setMobileOpen((value) => !value)}><span /><span /><span /></button>
      <nav id={`${id}-navigation`} aria-label={resources.menuLabel} className={`${styles.navigation} ${mobileOpen ? styles.navigationOpen : ""}`}>
        {!resolvedData ? <p className={styles.loading}>{resources.loadingMenuLabel}</p> : <ul className={styles.topLevel}>
          {resolvedData.items.map((item) => <li key={item.id}>{item.children?.length && item.id === "commerce" ? <MegaMenu item={item} onNavigate={close} /> : <MenuBranch item={item} onNavigate={close} />}</li>)}
          <li><Link href="/blog" onClick={close}>{resources.blogLabel}</Link></li>
          {config.showSearch ? <li><Link href="/search" onClick={close}>{resources.searchLabel}</Link></li> : null}
        </ul>}
      </nav>
    </div>
  </header>;
}
