import { moduleDefinitions, moduleRegistry } from "@/modules/registry.autogenerated";
import type { ModuleInstance, ModuleValues } from "@/modules/module.types";

function defaultsForConfig(name: string): ModuleValues {
  return Object.fromEntries(Object.entries(moduleDefinitions[name]?.config ?? {}).map(([key, field]) => [key, field.default ?? null]));
}

function defaultsForResources(name: string): ModuleValues {
  return Object.fromEntries(Object.entries(moduleDefinitions[name]?.resources ?? {}).map(([key, resource]) => [key, resource.value]));
}

export function ModuleRenderer({ modules, locale = process.env.DEFAULT_LOCALE ?? "en" }: { modules: ModuleInstance[]; locale?: string }) {
  return <>{modules.map((instance) => {
    if (instance.name === "__html" && instance.html) return <div className="wp-content" key={instance.id} dangerouslySetInnerHTML={{ __html: instance.html }} />;
    const Component = moduleRegistry[instance.name];
    if (!Component) return null;
    const language = locale.toLowerCase();
    const baseLanguage = language.split("-")[0];
    const localized = instance.resources[language] ?? instance.resources[baseLanguage] ?? instance.resources.en ?? {};
    return <Component key={instance.id} id={instance.id} locale={locale} config={{ ...defaultsForConfig(instance.name), ...instance.config }} resources={{ ...defaultsForResources(instance.name), ...localized }} />;
  })}</>;
}

export const defaultHeaderModule: ModuleInstance = { id: "default-global-header", name: "header", config: {}, resources: {} };
