/*---------------------------------------------------------------------------------------------
 * Copyright (c) Lumovy Technology Solutions. All rights reserved.
 *--------------------------------------------------------------------------------------------*/

import definition from "./navigation.definition.json";
import type { ModuleDataActionDefinition } from "../module.types";
import { loadDataAction } from "@/lib/api/data-actions/server";
import type { CategoryNode, NavigationData } from "./navigation.data";
import type { NavigationProps } from "./navigation.props.autogenerated";
import { NavigationView } from "./navigation.view";

export default async function NavigationModule(props: NavigationProps) {
  const mode =
    props.config.menuMode === "retail" || props.config.menuMode === "authored"
      ? props.config.menuMode
      : "all";
  const menuAction = definition.dataActions.menu as ModuleDataActionDefinition;
  const categoriesAction = definition.dataActions
    .categories as ModuleDataActionDefinition;
  const [menu, categories] = await Promise.all([
    loadDataAction<NavigationData>(menuAction, {
      mode,
      menuSlug: props.config.wordpressMenuSlug || "primary",
    }),
    mode === "authored"
      ? null
      : loadDataAction<CategoryNode[]>(categoriesAction, {
          presentation: "tree",
        }),
  ]);
  return (
    <NavigationView
      {...props}
      menuAction={menuAction}
      categoriesAction={categoriesAction}
      initialMenu={menu}
      initialCategories={categories}
    />
  );
}
