/*---------------------------------------------------------------------------------------------
 * Copyright (c) Lumovy Technology Solutions. All rights reserved.
 *--------------------------------------------------------------------------------------------*/

/* Generated by npm run modules:generate. Do not edit this file manually. */
import type { ModuleRuntimeProps } from "../module.types";
export type NavigationConfig = Record<string, string | number | boolean | null | string[]> & {
  menuMode: string;
  wordpressMenuSlug: string;
  showSearch: boolean;
};
export type NavigationResources = Record<string, string | number | boolean | null | string[]> & {
  menuLabel: string;
  openLabel: string;
  closeLabel: string;
  searchLabel: string;
  loadingLabel: string;
};
export type NavigationProps = ModuleRuntimeProps<NavigationConfig, NavigationResources>;
