/*---------------------------------------------------------------------------------------------
 * Copyright (c) Lumovy Technology Solutions. All rights reserved.
 *--------------------------------------------------------------------------------------------*/

"use client";
import Link from "next/link";
import { useMemo, useState } from "react";
import { useDataAction } from "@/lib/api/data-actions/client";
import type { ModuleDataActionDefinition } from "../module.types";
import type { NavigationProps } from "./navigation.props.autogenerated";
import type {
  CategoryNode,
  NavigationData,
  NavigationItem,
} from "./navigation.data";

function slugify(value: string) {
  return value
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}
function categoryItem(category: CategoryNode): NavigationItem {
  const label = category.Name || "Category";
  return {
    id: String(category.RecordId),
    label,
    href: `/${slugify(label)}`,
    audience: "retail",
    children: category.children.map(categoryItem),
  };
}
function Branch({ item, close }: { item: NavigationItem; close: () => void }) {
  if (!item.children?.length)
    return (
      <Link
        className="block rounded-lg px-3 py-2 hover:bg-zinc-100"
        href={item.href}
        onClick={close}
      >
        {item.label}
      </Link>
    );
  return (
    <details className="group relative">
      <summary className="flex cursor-pointer list-none items-center gap-1 rounded-lg px-3 py-2 font-medium hover:bg-zinc-100">
        {item.label}
        <span className="transition group-open:rotate-180">⌄</span>
      </summary>
      <div className="ml-3 min-w-56 border-l border-zinc-200 bg-white p-2 md:absolute md:right-0 md:top-full md:ml-0 md:rounded-xl md:border md:shadow-xl">
        {item.children.map((child) => (
          <Branch key={child.id} item={child} close={close} />
        ))}
      </div>
    </details>
  );
}
export function NavigationView({
  id,
  config,
  resources,
  menuAction,
  categoriesAction,
  initialMenu,
  initialCategories,
}: NavigationProps & {
  menuAction: ModuleDataActionDefinition;
  categoriesAction: ModuleDataActionDefinition;
  initialMenu: NavigationData | null;
  initialCategories: CategoryNode[] | null;
}) {
  const [open, setOpen] = useState(false);
  const mode =
    config.menuMode === "retail" || config.menuMode === "authored"
      ? config.menuMode
      : "all";
  const menu = useDataAction<NavigationData>(
    menuAction,
    { mode, menuSlug: config.wordpressMenuSlug || "primary" },
    initialMenu,
  );
  const categories = useDataAction<CategoryNode[]>(
    categoriesAction,
    { presentation: "tree" },
    initialCategories,
    mode !== "authored",
  );
  const items = useMemo(
    () =>
      (menu.data?.items ?? []).map((item) =>
        item.id === "commerce"
          ? { ...item, children: categories.data?.map(categoryItem) ?? [] }
          : item,
      ),
    [categories.data, menu.data],
  );
  return (
    <div className="flex justify-end">
      <button
        type="button"
        className="rounded-lg border border-zinc-300 px-3 py-2 md:hidden"
        aria-controls={`${id}-menu`}
        aria-expanded={open}
        onClick={() => setOpen(!open)}
      >
        {open ? resources.closeLabel : resources.openLabel}
      </button>
      <nav
        id={`${id}-menu`}
        aria-label={resources.menuLabel}
        className={`${open ? "block" : "hidden"} absolute inset-x-0 top-full border-b bg-white p-4 shadow-lg md:static md:block md:border-0 md:bg-transparent md:p-0 md:shadow-none`}
      >
        <div className="flex flex-col gap-1 md:flex-row md:items-center md:justify-end">
          {menu.isLoading ? (
            <span className="px-3 py-2 text-sm text-zinc-500">
              {resources.loadingLabel}
            </span>
          ) : (
            items.map((item) => (
              <Branch key={item.id} item={item} close={() => setOpen(false)} />
            ))
          )}
          {config.showSearch ? (
            <Link
              className="rounded-lg px-3 py-2 font-medium hover:bg-zinc-100"
              href="/search"
            >
              {resources.searchLabel}
            </Link>
          ) : null}
        </div>
      </nav>
    </div>
  );
}
