/*---------------------------------------------------------------------------------------------
 * Copyright (c) Lumovy Technology Solutions. All rights reserved.
 *--------------------------------------------------------------------------------------------*/

"use client";

import Link from "next/link";
import Image from "next/image";
import { useEffect, useId, useMemo, useRef, useState } from "react";
import { useDataAction } from "@/lib/api/data-actions/client";
import type { ModuleDataActionDefinition } from "../module.types";
import type { NavigationProps } from "./navigation.props.autogenerated";
import type { CategoryNode, NavigationData, NavigationItem } from "./navigation.data";
import styles from "./navigation.module.scss";

function slugify(value: string) { return value.toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, ""); }
function categoryItem(category: CategoryNode): NavigationItem { const label = category.Name || "Category"; return { id: String(category.RecordId), label, href: `/${slugify(label)}`, audience: "retail", description: category.LocalizedDescription || undefined, imageUrl: category.imageUrl, children: category.children.map(categoryItem) }; }

function Chevron({ open = false }: { open?: boolean }) { return <svg aria-hidden="true" className={`h-3.5 w-3.5 transition-transform duration-300 ${open ? "rotate-180" : ""}`} fill="none" viewBox="0 0 20 20"><path d="m5 7.5 5 5 5-5" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.8" /></svg>; }
function SearchIcon() { return <svg aria-hidden="true" className="h-[18px] w-[18px]" fill="none" viewBox="0 0 24 24"><circle cx="11" cy="11" r="6.5" stroke="currentColor" strokeWidth="1.8" /><path d="m16 16 4 4" stroke="currentColor" strokeLinecap="round" strokeWidth="1.8" /></svg>; }

function FeatureBranch({ item, depth = 0, close }: { item: NavigationItem; depth?: number; close: () => void }) {
  const children = item.children ?? [];
  return <div className={depth === 0 ? "min-w-0" : "border-l border-black/8 pl-3"}>
    {depth === 0 && item.imageUrl ? <Link className="group/image relative mb-3 block aspect-[16/9] overflow-hidden rounded-xl bg-zinc-100" href={item.href} onClick={close}><Image alt={item.label} className="object-cover transition duration-500 ease-out group-hover/image:scale-105" fill sizes="(min-width: 1024px) 20vw, 40vw" src={item.imageUrl} unoptimized /><span className="absolute inset-0 bg-gradient-to-t from-black/20 to-transparent opacity-0 transition group-hover/image:opacity-100" /></Link> : null}
    <Link className={`${depth === 0 ? "text-[15px] font-semibold text-zinc-950" : "text-sm font-medium text-zinc-700"} group/link inline-flex max-w-full items-center gap-1.5 rounded-md py-1.5 outline-none transition hover:text-black focus-visible:ring-2 focus-visible:ring-black/20`} href={item.href} onClick={close}><span className="truncate">{item.label}</span><span aria-hidden="true" className="translate-x-0 text-zinc-300 opacity-0 transition group-hover/link:translate-x-0.5 group-hover/link:opacity-100">→</span></Link>
    {depth === 0 && item.description ? <p className="mb-2 line-clamp-2 text-xs leading-relaxed text-zinc-500">{item.description}</p> : null}
    {children.length ? <div className={`${depth === 0 ? "mt-1" : "mt-0.5"} space-y-0.5`}>{children.map((child) => <FeatureBranch close={close} depth={depth + 1} item={child} key={child.id} />)}</div> : null}
  </div>;
}

function DesktopItem({ item, closeAll }: { item: NavigationItem; closeAll: () => void }) {
  const [open, setOpen] = useState(false);
  const panelId = useId();
  const rootRef = useRef<HTMLDivElement>(null);
  const hasChildren = Boolean(item.children?.length);
  useEffect(() => { if (!open) return; const dismiss = (event: PointerEvent) => { if (!rootRef.current?.contains(event.target as Node)) setOpen(false); }; const escape = (event: KeyboardEvent) => { if (event.key === "Escape") setOpen(false); }; document.addEventListener("pointerdown", dismiss); document.addEventListener("keydown", escape); return () => { document.removeEventListener("pointerdown", dismiss); document.removeEventListener("keydown", escape); }; }, [open]);
  if (!hasChildren) return <Link className="rounded-full px-3.5 py-2 text-[14px] font-medium text-zinc-700 outline-none transition duration-200 hover:bg-black/[0.045] hover:text-black focus-visible:ring-2 focus-visible:ring-black/20" href={item.href} onClick={closeAll}>{item.label}</Link>;
  return <div className="relative" ref={rootRef}>
    <div className={`flex items-center rounded-full transition duration-200 ${open ? "bg-black/[0.055] text-black" : "text-zinc-700 hover:bg-black/[0.045] hover:text-black"}`}>
      <Link className="rounded-l-full py-2 pl-3.5 pr-1 text-[14px] font-medium outline-none focus-visible:ring-2 focus-visible:ring-black/20" href={item.href} onClick={() => { setOpen(false); closeAll(); }}>{item.label}</Link>
      <button aria-controls={panelId} aria-expanded={open} aria-label={`Open ${item.label} menu`} className="rounded-r-full py-2 pl-1 pr-3 outline-none focus-visible:ring-2 focus-visible:ring-black/20" onClick={() => setOpen((value) => !value)} type="button"><Chevron open={open} /></button>
    </div>
    <div aria-hidden={!open} className={`${styles.featurePanel} ${open ? styles.featurePanelOpen : ""}`} id={panelId} inert={!open}>
      <div className="mb-5 flex items-end justify-between gap-6 border-b border-black/8 pb-4"><div><p className="text-[11px] font-semibold uppercase tracking-[0.18em] text-zinc-400">Explore</p><Link className="mt-1 inline-flex items-center gap-2 text-xl font-semibold tracking-tight text-zinc-950 hover:underline" href={item.href} onClick={() => { setOpen(false); closeAll(); }}>{item.label}<span aria-hidden="true">→</span></Link></div><p className="hidden max-w-xs text-right text-xs leading-relaxed text-zinc-500 lg:block">Discover collections, categories, and everything inside.</p></div>
      <div className="grid max-h-[min(65vh,34rem)] grid-cols-2 gap-x-8 gap-y-6 overflow-y-auto overscroll-contain pr-2 lg:grid-cols-3 xl:grid-cols-4">{item.children?.map((child) => <FeatureBranch close={() => { setOpen(false); closeAll(); }} item={child} key={child.id} />)}</div>
    </div>
  </div>;
}

function MobileBranch({ item, close, depth = 0 }: { item: NavigationItem; close: () => void; depth?: number }) {
  const [open, setOpen] = useState(false);
  const panelId = useId();
  const children = item.children ?? [];
  return <div className={depth ? "ml-4 border-l border-black/8 pl-3" : "border-b border-black/[0.055] last:border-0"}>
    <div className="flex min-h-12 items-center gap-1"><Link className={`${depth ? "text-[15px]" : "text-[17px]"} flex-1 rounded-lg py-3 font-medium text-zinc-900 outline-none transition active:opacity-50 focus-visible:ring-2 focus-visible:ring-black/20`} href={item.href} onClick={close}>{item.label}</Link>{children.length ? <button aria-controls={panelId} aria-expanded={open} aria-label={`Open ${item.label} submenu`} className="grid h-10 w-10 place-items-center rounded-full bg-black/[0.045] text-zinc-700 transition active:scale-95" onClick={() => setOpen((value) => !value)} type="button"><Chevron open={open} /></button> : null}</div>
    {children.length ? <div className={`${styles.mobileChildren} ${open ? styles.mobileChildrenOpen : ""}`} id={panelId}><div className="pb-2">{children.map((child) => <MobileBranch close={close} depth={depth + 1} item={child} key={child.id} />)}</div></div> : null}
  </div>;
}

export function NavigationView({ id, config, resources, menuAction, categoriesAction, initialMenu, initialCategories }: NavigationProps & { menuAction: ModuleDataActionDefinition; categoriesAction: ModuleDataActionDefinition; initialMenu: NavigationData | null; initialCategories: CategoryNode[] | null }) {
  const [open, setOpen] = useState(false);
  const mode = config.menuMode === "retail" || config.menuMode === "authored" ? config.menuMode : "all";
  const menu = useDataAction<NavigationData>(menuAction, { mode, menuSlug: config.wordpressMenuSlug || "primary" }, initialMenu);
  const categories = useDataAction<CategoryNode[]>(categoriesAction, { presentation: "tree" }, initialCategories, mode !== "authored");
  const items = useMemo(() => { const roots = categories.data ?? []; const visibleCategories = roots.length === 1 && roots[0].children.length ? roots[0].children : roots; return (menu.data?.items ?? []).map((item) => item.id === "commerce" ? { ...item, children: visibleCategories.map(categoryItem) } : item); }, [categories.data, menu.data]);
  useEffect(() => { if (!open) return; const previous = document.body.style.overflow; document.body.style.overflow = "hidden"; const escape = (event: KeyboardEvent) => { if (event.key === "Escape") setOpen(false); }; document.addEventListener("keydown", escape); return () => { document.body.style.overflow = previous; document.removeEventListener("keydown", escape); }; }, [open]);
  const close = () => setOpen(false);
  return <div className="flex justify-end">
    <button aria-controls={`${id}-menu`} aria-expanded={open} aria-label={open ? resources.closeLabel : resources.openLabel} className="relative z-20 grid h-10 w-10 place-items-center rounded-full bg-black/[0.055] text-zinc-900 outline-none transition duration-200 hover:bg-black/10 active:scale-95 focus-visible:ring-2 focus-visible:ring-black/25 md:hidden" onClick={() => setOpen((value) => !value)} type="button"><span className="sr-only">{open ? resources.closeLabel : resources.openLabel}</span><span className="relative block h-4 w-5"><span className={`absolute left-0 top-1 block h-px w-5 bg-current transition duration-300 ${open ? "translate-y-[3px] rotate-45" : ""}`} /><span className={`absolute bottom-1 left-0 block h-px w-5 bg-current transition duration-300 ${open ? "-translate-y-[3px] -rotate-45" : ""}`} /></span></button>
    <nav aria-label={resources.menuLabel} id={`${id}-menu`}>
      <div className="hidden items-center justify-end gap-0.5 md:flex">{menu.isLoading ? <span className="px-4 py-2 text-sm text-zinc-400">{resources.loadingLabel}</span> : items.map((item) => <DesktopItem closeAll={close} item={item} key={item.id} />)}{config.showSearch ? <Link aria-label={resources.searchLabel} className="ml-1 grid h-9 w-9 place-items-center rounded-full text-zinc-600 outline-none transition hover:bg-black/[0.055] hover:text-black focus-visible:ring-2 focus-visible:ring-black/20" href="/search"><SearchIcon /><span className="sr-only">{resources.searchLabel}</span></Link> : null}</div>
      <button aria-hidden={!open} className={`${styles.backdrop} ${open ? styles.backdropOpen : ""}`} onClick={close} tabIndex={open ? 0 : -1} type="button" />
      <div aria-hidden={!open} className={`${styles.mobilePanel} ${open ? styles.mobilePanelOpen : ""}`} inert={!open}><button aria-label={resources.closeLabel} className="absolute right-4 top-4 grid h-10 w-10 place-items-center rounded-full bg-black/[0.055] text-xl text-zinc-700 transition active:scale-95" onClick={close} type="button">×</button><div className="mb-3 flex items-center justify-between px-1"><p className="text-[11px] font-semibold uppercase tracking-[0.18em] text-zinc-400">{resources.menuLabel}</p></div>{menu.isLoading ? <p className="py-8 text-center text-sm text-zinc-500">{resources.loadingLabel}</p> : <div>{items.map((item) => <MobileBranch close={close} item={item} key={item.id} />)}</div>}{config.showSearch ? <Link className="mt-4 flex items-center justify-between rounded-2xl bg-zinc-950 px-5 py-4 font-medium text-white transition active:scale-[0.99]" href="/search" onClick={close}><span>{resources.searchLabel}</span><SearchIcon /></Link> : null}</div>
    </nav>
  </div>;
}
