/*---------------------------------------------------------------------------------------------
 * Copyright (c) Lumovy Technology Solutions. All rights reserved.
 *--------------------------------------------------------------------------------------------*/

import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

const [name, moduleName, execution = "client"] = process.argv.slice(2);
if (!name || !/^[a-z][a-z0-9-]*$/.test(name) || (moduleName && !/^[a-z][a-z0-9-]*$/.test(moduleName)) || !["client", "server"].includes(execution)) {
  console.error("Usage: npm run api:create -- <api-name> [module-name] [client|server]");
  console.error("Example: npm run api:create -- products product-list client");
  process.exit(1);
}

const functionName = name.split("-").map((part) => part[0].toUpperCase() + part.slice(1)).join("");
const directory = path.join(process.cwd(), "app", "api", "commerce", name);
const copyright = `/*---------------------------------------------------------------------------------------------\n * Copyright (c) Lumovy Technology Solutions. All rights reserved.\n *--------------------------------------------------------------------------------------------*/\n\n`;
await mkdir(directory, { recursive: false });

await writeFile(path.join(directory, `${functionName}.ts`), `${copyright}import { commerceRequest } from "@/lib/api/commerce/request";

// EDIT HERE: replace this small response type with the generated Commerce type you need.
interface ${functionName}Response { value?: unknown[] }

// EDIT ONLY THIS FUNCTION: path, method, payload, query params and returned data.
export async function ${functionName}(request: Request) {
  const search = new URL(request.url).searchParams;
  const response = await commerceRequest<${functionName}Response>({
    path: "/${functionName}", // 1. Commerce API path
    method: "POST", // 2. GET, POST, PUT, PATCH or DELETE
    payload: (config) => ({ channelId: config.channelId }), // 3. Static or dynamic payload
    params: { $top: search.get("top") || "100" }, // 4. Commerce query parameters
  });
  return response.value ?? response; // 5. Data returned to the module
}
`);
await writeFile(path.join(directory, "route.ts"), `${copyright}import { createGetRoute } from "@/lib/api/route";
import { ${functionName} } from "./${functionName}";

// Generated plumbing. You normally do not edit this file.
export const GET = createGetRoute(${functionName});
`);

if (moduleName) {
  const definitionFile = path.join(process.cwd(), "modules", moduleName, `${moduleName}.definition.json`);
  const definition = JSON.parse(await readFile(definitionFile, "utf8"));
  definition.dataActions ??= {};
  definition.dataActions[name] = { endpoint: `/api/commerce/${name}`, method: "GET", execution };
  await writeFile(definitionFile, JSON.stringify(definition, null, 2) + "\n");
}

console.log(`Created /api/commerce/${name}.`);
console.log(`Edit only app/api/commerce/${name}/${functionName}.ts.`);
if (moduleName) console.log(`Connected it to modules/${moduleName} with ${execution} execution.`);
else console.log(`Connect it later: npm run action:create -- <module> ${name} /api/commerce/${name} client`);
