/*---------------------------------------------------------------------------------------------
 * Copyright (c) Lumovy Technology Solutions. All rights reserved.
 *--------------------------------------------------------------------------------------------*/

import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

const name = process.argv[2];
if (!name || !/^[a-z][a-z0-9-]*$/.test(name)) {
  console.error("Usage: npm run module:create -- <lowercase-module-name>");
  process.exit(1);
}
const title = name.split("-").map((part) => part[0].toUpperCase() + part.slice(1)).join(" ");
const directory = path.join(process.cwd(), "modules", name);
await mkdir(directory, { recursive: false });
const copyright = `/*---------------------------------------------------------------------------------------------\n * Copyright (c) Lumovy Technology Solutions. All rights reserved.\n *--------------------------------------------------------------------------------------------*/\n\n`;
await writeFile(path.join(directory, `${name}.definition.json`), JSON.stringify({ schemaVersion: 1, friendlyName: title, name, description: `${title} module.`, categories: ["content"], tags: [name], config: { title: { friendlyName: "Title", type: "string", default: title, group: "Content" } }, resources: {}, dataActions: {} }, null, 2) + "\n");
await writeFile(path.join(directory, `${name}.data.ts`), `${copyright}// Step 1: Put API response and custom types here. Delete this file if none are needed.\nexport interface ${title.replace(/\s/g, "")}Data { message: string }\n`);
await writeFile(path.join(directory, `${name}.tsx`), `${copyright}import type { ${title.replace(/\s/g, "")}Props } from "./${name}.props.autogenerated";\nimport { ${title.replace(/\s/g, "")}View } from "./${name}.view";\n\nexport default function ${title.replace(/\s/g, "")}Module(props: ${title.replace(/\s/g, "")}Props) { return <${title.replace(/\s/g, "")}View {...props} />; }\n`);
await writeFile(path.join(directory, `${name}.view.tsx`), `${copyright}import type { ${title.replace(/\s/g, "")}Props } from "./${name}.props.autogenerated";\n\nexport function ${title.replace(/\s/g, "")}View({ config }: ${title.replace(/\s/g, "")}Props) { return <section><h2>{config.title}</h2></section>; }\n`);
await writeFile(path.join(directory, `${name}.module.scss`), `${copyright}.root { width: 100%; }\n`);
console.log(`Created ${name}. Run npm run modules:generate.`);
