import { readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

const root = process.cwd();
const modulesRoot = path.join(root, "modules");
const entries = await readdir(modulesRoot, { withFileTypes: true });
const definitions = [];
const copyright = `/*---------------------------------------------------------------------------------------------
 * Copyright (c) Lumovy Technology Solutions. All rights reserved.
 *--------------------------------------------------------------------------------------------*/`;
const allowedTypes = new Set(["string", "text", "number", "boolean", "color", "select", "url", "image"]);
const tsType = (field) => field.type === "number" ? "number" : field.type === "boolean" ? "boolean" : "string";
const pascal = (value) => value.split(/[-_]/).map((part) => part.charAt(0).toUpperCase() + part.slice(1)).join("");

for (const entry of entries.filter((item) => item.isDirectory()).sort((a, b) => a.name.localeCompare(b.name))) {
  const definition = JSON.parse(await readFile(path.join(modulesRoot, entry.name, `${entry.name}.definition.json`), "utf8"));
  if (definition.schemaVersion !== 1 || definition.name !== entry.name || !/^[a-z][a-z0-9-]*$/.test(definition.name) || !definition.friendlyName || !definition.description) throw new Error(`Invalid module definition: ${entry.name}`);
  for (const [key, field] of Object.entries(definition.config || {})) if (!field.friendlyName || !allowedTypes.has(field.type)) throw new Error(`Invalid config field ${definition.name}.${key}`);
  for (const [key, slot] of Object.entries(definition.slots || {})) if (!slot.friendlyName || !Array.isArray(slot.allowedModules) || !slot.allowedModules.length) throw new Error(`Invalid slot ${definition.name}.${key}`);
  for (const [key, action] of Object.entries(definition.dataActions || {})) if (action.method !== "GET" || !action.endpoint?.startsWith("/api/") || !["server", "client"].includes(action.execution)) throw new Error(`Invalid data action ${definition.name}.${key}`);
  const name = pascal(definition.name);
  const config = Object.entries(definition.config).map(([key, field]) => `  ${key}: ${tsType(field)};`).join("\n");
  const resources = Object.keys(definition.resources).map((key) => `  ${key}: string;`).join("\n");
  await writeFile(path.join(modulesRoot, entry.name, `${entry.name}.props.autogenerated.ts`), `${copyright}\n\n/* Generated by npm run modules:generate. Do not edit this file manually. */\nimport type { ModuleRuntimeProps } from "../module.types";\nexport type ${name}Config = Record<string, string | number | boolean | null | string[]> & {\n${config}\n};\nexport type ${name}Resources = Record<string, string | number | boolean | null | string[]> & {\n${resources}\n};\nexport type ${name}Props = ModuleRuntimeProps<${name}Config, ${name}Resources>;\n`);
  definitions.push(definition);
}

const imports = definitions.map((definition, index) => `import Module${index} from "./${definition.name}/${definition.name}";`).join("\n");
const registry = definitions.map((definition, index) => `  "${definition.name}": Module${index} as ModuleComponent,`).join("\n");
await writeFile(path.join(modulesRoot, "registry.autogenerated.ts"), `${copyright}\n\n/* Generated by npm run modules:generate. Do not edit this file manually. */\n${imports}\nimport type { ModuleComponent, ModuleDefinition } from "./module.types";\nexport const moduleRegistry: Record<string, ModuleComponent> = {\n${registry}\n};\nexport const moduleDefinitions: Record<string, ModuleDefinition> = Object.fromEntries((${JSON.stringify(definitions)} as ModuleDefinition[]).map((definition) => [definition.name, definition]));\n`);
await writeFile(path.join(root, "wordpress-plugin/dynamics-headless-connector/modules-manifest.json"), JSON.stringify(definitions, null, 2) + "\n");
console.log(`Generated ${definitions.length} module definition(s).`);
