/*---------------------------------------------------------------------------------------------
 * Copyright (c) Lumovy Technology Solutions. All rights reserved.
 *--------------------------------------------------------------------------------------------*/

/* Generated by npm run modules:generate. Do not edit this file manually. */
import type { ModuleRuntimeProps } from "../module.types";
export type BuyboxConfig = Record<string, string | number | boolean | null | string[]> & {
  currency: string;
  showDescription: boolean;
  showProductNumber: boolean;
  className: string;
};
export type BuyboxResources = Record<string, string | number | boolean | null | string[]> & {
  loadingLabel: string;
  errorLabel: string;
  missingLabel: string;
  productNumberLabel: string;
};
export type BuyboxProps = ModuleRuntimeProps<BuyboxConfig, BuyboxResources>;
