/*---------------------------------------------------------------------------------------------
 * Copyright (c) Lumovy Technology Solutions. All rights reserved.
 *--------------------------------------------------------------------------------------------*/

import definition from "./buybox.definition.json";
import type { ModuleDataActionDefinition } from "../module.types";
import type { BuyboxProps } from "./buybox.props.autogenerated";
import { BuyboxView } from "./buybox.view";

export default function BuyboxModule(props: BuyboxProps) {
  return <BuyboxView {...props} productAction={definition.dataActions.product as ModuleDataActionDefinition} />;
}
