/*---------------------------------------------------------------------------------------------
 * Copyright (c) Lumovy Technology Solutions. All rights reserved.
 *--------------------------------------------------------------------------------------------*/

"use client";

import Image from "next/image";
import { useCatalogRoute } from "@/lib/commerce/catalog-context";
import { useDataAction } from "@/lib/api/data-actions/client";
import type { ModuleDataActionDefinition } from "../module.types";
import type { BuyboxProduct } from "./buybox.data";
import type { BuyboxProps } from "./buybox.props.autogenerated";

export function BuyboxView({ config, resources, slots, productAction }: BuyboxProps & { productAction: ModuleDataActionDefinition }) {
  const { productId } = useCatalogRoute();
  const query = useDataAction<BuyboxProduct[]>(productAction, { productIds: productId ? String(productId) : undefined }, undefined, Boolean(productId));
  const product = query.data?.[0];
  const price = product ? (product.AdjustedPrice ?? product.Price ?? product.BasePrice) : 0;
  let formattedPrice = String(price);
  try { formattedPrice = new Intl.NumberFormat(undefined, { style: "currency", currency: String(config.currency || "USD") }).format(price); } catch { /* Use the raw numeric price for an invalid authored currency. */ }
  if (!productId) return <section className={`site-shell py-10 ${config.className}`}><p className="rounded-2xl bg-amber-50 p-6 text-amber-900">{resources.missingLabel}</p></section>;
  if (query.isLoading) return <section className={`site-shell py-10 ${config.className}`}><p className="rounded-2xl bg-zinc-50 p-6 text-black/60" role="status">{resources.loadingLabel}</p></section>;
  if (query.isError || !product) return <section className={`site-shell py-10 ${config.className}`}><p className="rounded-2xl bg-red-50 p-6 text-red-800" role="alert">{resources.errorLabel}</p></section>;
  return <section className={`site-shell py-10 ${config.className}`}>
    <div className="grid items-start gap-10 lg:grid-cols-[minmax(0,1.15fr)_minmax(20rem,.85fr)] lg:gap-16">
      <div>{slots["media-gallery"] ?? (product.imageUrl ? <div className="relative aspect-square overflow-hidden rounded-3xl bg-zinc-100"><Image alt={product.Name || "Product"} className="object-contain" fill priority sizes="(min-width: 1024px) 55vw, 100vw" src={product.imageUrl} unoptimized /></div> : null)}</div>
      <div className="lg:sticky lg:top-24"><div className="border-b border-black/10 pb-6">{config.showProductNumber && product.ProductNumber ? <p className="text-xs font-semibold uppercase tracking-[0.16em] text-black/45">{resources.productNumberLabel}: {product.ProductNumber}</p> : null}<h1 className="mt-3 text-4xl font-semibold tracking-[-0.035em] text-zinc-950 sm:text-5xl">{product.Name || `Product ${product.RecordId}`}</h1><p className="mt-5 text-2xl font-medium tracking-tight text-zinc-900">{formattedPrice}</p>{config.showDescription && product.Description ? <p className="mt-6 text-base leading-7 text-black/65">{product.Description}</p> : null}</div>
        <div className="space-y-6 py-6">{slots["text-blocks"]}{slots["store-selector"]}{slots["social-share"]}</div>
      </div>
    </div>
    {slots["product-specification"] || slots["product-comparison"] ? <div className="mt-16 space-y-12 border-t border-black/10 pt-12">{slots["product-specification"]}{slots["product-comparison"]}</div> : null}
  </section>;
}
