/*---------------------------------------------------------------------------------------------
 * Copyright (c) Lumovy Technology Solutions. All rights reserved.
 *--------------------------------------------------------------------------------------------*/

import definition from "./media-gallery.definition.json";
import type { ModuleDataActionDefinition } from "../module.types";
import type { MediaGalleryProps } from "./media-gallery.props.autogenerated";
import { MediaGalleryView } from "./media-gallery.view";

export default function MediaGalleryModule(props: MediaGalleryProps) {
  return <MediaGalleryView {...props} mediaAction={definition.dataActions.media as ModuleDataActionDefinition} />;
}
