/*---------------------------------------------------------------------------------------------
 * Copyright (c) Lumovy Technology Solutions. All rights reserved.
 *--------------------------------------------------------------------------------------------*/

/* Generated by npm run modules:generate. Do not edit this file manually. */
import type { ModuleRuntimeProps } from "../module.types";
export type MediaGalleryConfig = Record<string, string | number | boolean | null | string[]> & {
  imageFit: string;
  showThumbnails: boolean;
  className: string;
};
export type MediaGalleryResources = Record<string, string | number | boolean | null | string[]> & {
  loadingLabel: string;
  emptyLabel: string;
  errorLabel: string;
  missingLabel: string;
};
export type MediaGalleryProps = ModuleRuntimeProps<MediaGalleryConfig, MediaGalleryResources>;
