/*---------------------------------------------------------------------------------------------
 * Copyright (c) Lumovy Technology Solutions. All rights reserved.
 *--------------------------------------------------------------------------------------------*/

"use client";

import Image from "next/image";
import { useState } from "react";
import { useCatalogRoute } from "@/lib/commerce/catalog-context";
import { useDataAction } from "@/lib/api/data-actions/client";
import type { ModuleDataActionDefinition } from "../module.types";
import type { GalleryMedia } from "./media-gallery.data";
import type { MediaGalleryProps } from "./media-gallery.props.autogenerated";

export function MediaGalleryView({
  config,
  resources,
  mediaAction,
}: MediaGalleryProps & { mediaAction: ModuleDataActionDefinition }) {
  const { productId } = useCatalogRoute();
  const query = useDataAction<GalleryMedia[]>(
    mediaAction,
    { recordId: productId },
    undefined,
    Boolean(productId),
  );
  const media = (query.data ?? []).filter((item) => item.imageUrl);
  const [selected, setSelected] = useState(0);
  if (!productId)
    return (
      <div
        className={`rounded-2xl bg-amber-50 p-6 text-amber-900 ${config.className}`}
      >
        {resources.missingLabel}
      </div>
    );
  if (query.isLoading)
    return (
      <div
        className={`aspect-square animate-pulse rounded-3xl bg-zinc-100 p-6 text-black/45 ${config.className}`}
        role="status"
      >
        {resources.loadingLabel}
      </div>
    );
  if (query.isError)
    return (
      <div
        className={`rounded-2xl bg-red-50 p-6 text-red-800 ${config.className}`}
        role="alert"
      >
        {resources.errorLabel}
      </div>
    );
  if (!media.length)
    return (
      <div
        className={`rounded-2xl bg-zinc-50 p-6 text-black/60 ${config.className}`}
      >
        {resources.emptyLabel}
      </div>
    );
  const activeIndex = selected < media.length ? selected : 0;
  const active = media[activeIndex];
  return (
    <div className={config.className}>
      <div className="relative aspect-square overflow-hidden rounded-3xl bg-zinc-100">
        <Image
          alt={active.AltText || "Product image"}
          className={
            config.imageFit === "cover" ? "object-cover" : "object-contain"
          }
          fill
          priority
          sizes="(min-width: 1024px) 55vw, 100vw"
          src={active.imageUrl!}
          unoptimized
        />
      </div>
      {config.showThumbnails && media.length > 1 ? (
        <div className="mt-4 grid grid-cols-5 gap-3 sm:grid-cols-6">
          {media.map((item, index) => (
            <button
              aria-label={`View image ${index + 1}`}
              aria-pressed={activeIndex === index}
              className={`relative aspect-square overflow-hidden rounded-xl bg-zinc-100 transition ${activeIndex === index ? "ring-2 ring-zinc-950 ring-offset-2" : "opacity-65 hover:opacity-100"}`}
              key={`${item.Uri}-${index}`}
              onClick={() => setSelected(index)}
              type="button"
            >
              <Image
                alt=""
                className="object-cover"
                fill
                sizes="8rem"
                src={item.imageUrl!}
                unoptimized
              />
            </button>
          ))}
        </div>
      ) : null}
    </div>
  );
}
