/*---------------------------------------------------------------------------------------------
 * Copyright (c) Lumovy Technology Solutions. All rights reserved.
 *--------------------------------------------------------------------------------------------*/
import type { ContainerProps } from "./container.props.autogenerated";
export default function Container({ config, slots }: ContainerProps) {
  const backgroundSize = config.backgroundFit === "contain" || config.backgroundFit === "auto" ? config.backgroundFit : "cover";
  return <section className={`${config.width === "boxed" ? "site-shell" : "w-full"} ${config.className}`} style={{ backgroundColor: config.backgroundColor, backgroundImage: config.backgroundImage ? `url(${config.backgroundImage})` : undefined, backgroundPosition: "center", backgroundRepeat: "no-repeat", backgroundSize }}><div className={`${config.layout === "flow" ? "flex flex-wrap items-start" : "flex flex-col"} gap-6`}>{slots.content}</div></section>;
}
