/*---------------------------------------------------------------------------------------------
 * Copyright (c) Lumovy Technology Solutions. All rights reserved.
 *--------------------------------------------------------------------------------------------*/

/* Generated by npm run modules:generate. Do not edit this file manually. */
import type { ModuleRuntimeProps } from "../module.types";
export type ContainerConfig = Record<string, string | number | boolean | null | string[]> & {
  layout: string;
  width: string;
  backgroundColor: string;
  backgroundImage: string;
  backgroundFit: string;
  className: string;
};
export type ContainerResources = Record<string, string | number | boolean | null | string[]> & {

};
export type ContainerProps = ModuleRuntimeProps<ContainerConfig, ContainerResources>;
