/*---------------------------------------------------------------------------------------------
 * Copyright (c) Lumovy Technology Solutions. All rights reserved.
 *--------------------------------------------------------------------------------------------*/

/* Generated by npm run modules:generate. Do not edit this file manually. */
import type { ModuleRuntimeProps } from "../module.types";
export type BreadcrumbConfig = Record<string, string | number | boolean | null | string[]> & {
  showHome: boolean;
  separator: string;
  className: string;
};
export type BreadcrumbResources = Record<string, string | number | boolean | null | string[]> & {
  homeLabel: string;
};
export type BreadcrumbProps = ModuleRuntimeProps<BreadcrumbConfig, BreadcrumbResources>;
