/*---------------------------------------------------------------------------------------------
 * Copyright (c) Lumovy Technology Solutions. All rights reserved.
 *--------------------------------------------------------------------------------------------*/

import type { BreadcrumbProps } from "./breadcrumb.props.autogenerated";
import { BreadcrumbView } from "./breadcrumb.view";

export default function BreadcrumbModule(props: BreadcrumbProps) {
  return <BreadcrumbView {...props} />;
}
