/*---------------------------------------------------------------------------------------------
 * Copyright (c) Lumovy Technology Solutions. All rights reserved.
 *--------------------------------------------------------------------------------------------*/

"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";
import type { BreadcrumbProps } from "./breadcrumb.props.autogenerated";

function labelFor(segment: string) {
  return decodeURIComponent(segment)
    .replaceAll("-", " ")
    .replace(/\b\w/g, (letter) => letter.toUpperCase());
}

export function BreadcrumbView({ config, resources }: BreadcrumbProps) {
  const pathname = usePathname();
  const segments = pathname.split("/").filter(Boolean);
  const items = segments.map((segment, index) => ({
    label: labelFor(segment),
    href: `/${segments.slice(0, index + 1).join("/")}`,
  }));
  if (config.showHome) items.unshift({ label: resources.homeLabel, href: "/" });
  if (items.length < 2) return null;
  return (
    <nav
      aria-label="Breadcrumb"
      className={`site-shell py-4 text-sm text-black/60 ${config.className}`}
    >
      <ol className="flex flex-wrap items-center gap-2">
        {items.map((item, index) => {
          const current = index === items.length - 1;
          return (
            <li className="flex items-center gap-2" key={item.href}>
              {index ? (
                <span aria-hidden="true">{config.separator}</span>
              ) : null}
              {current ? (
                <span aria-current="page">{item.label}</span>
              ) : (
                <Link
                  className="hover:text-black hover:underline"
                  href={item.href}
                >
                  {item.label}
                </Link>
              )}
            </li>
          );
        })}
      </ol>
    </nav>
  );
}
