/*---------------------------------------------------------------------------------------------
 * Copyright (c) Lumovy Technology Solutions. All rights reserved.
 *--------------------------------------------------------------------------------------------*/
import type { PageLayoutProps } from "./page-layout.props.autogenerated";
export default function PageLayout({ config, slots }: PageLayoutProps) { return <div className={config.className}><div data-page-slot="header">{slots.header}</div><div data-page-slot="sub-header">{slots["sub-header"]}</div><main data-page-slot="main">{slots.main}</main><div data-page-slot="sub-footer">{slots["sub-footer"]}</div><div data-page-slot="footer">{slots.footer}</div></div>; }
