/*---------------------------------------------------------------------------------------------
 * Copyright (c) Lumovy Technology Solutions. All rights reserved.
 *--------------------------------------------------------------------------------------------*/

/* Generated by npm run modules:generate. Do not edit this file manually. */
import type { ModuleRuntimeProps } from "../module.types";
export type PageLayoutConfig = Record<string, string | number | boolean | null | string[]> & {
  className: string;
};
export type PageLayoutResources = Record<string, string | number | boolean | null | string[]> & {

};
export type PageLayoutProps = ModuleRuntimeProps<PageLayoutConfig, PageLayoutResources>;
