/*---------------------------------------------------------------------------------------------
 * Copyright (c) Lumovy Technology Solutions. All rights reserved.
 *--------------------------------------------------------------------------------------------*/
import type { PageLayoutProps } from "./page-layout.props.autogenerated";
export default function PageLayout({ config, slots }: PageLayoutProps) { return <div className={config.className}>{slots.header ? <header className="contents" data-page-slot="header">{slots.header}</header> : null}{slots["sub-header"] ? <div data-page-slot="sub-header">{slots["sub-header"]}</div> : null}<main data-page-slot="main">{slots.main}</main>{slots["sub-footer"] ? <div data-page-slot="sub-footer">{slots["sub-footer"]}</div> : null}{slots.footer ? <footer data-page-slot="footer">{slots.footer}</footer> : null}</div>; }
