/*---------------------------------------------------------------------------------------------
 * Copyright (c) Lumovy Technology Solutions. All rights reserved.
 *--------------------------------------------------------------------------------------------*/

import { createHash, timingSafeEqual } from "node:crypto";
import { moduleDefinitions } from "@/modules/registry.autogenerated";

function validSecret(supplied: string | null) {
  const expected = process.env.WORDPRESS_REVALIDATION_SECRET;
  if (!expected || !supplied) return false;
  const left = Buffer.from(supplied);
  const right = Buffer.from(expected);
  return left.length === right.length && timingSafeEqual(left, right);
}

export function GET(request: Request) {
  if (!validSecret(request.headers.get("x-wordpress-secret"))) return Response.json({ ok: false, error: "Unauthorized" }, { status: 401 });
  const modules = Object.values(moduleDefinitions).sort((a, b) => a.name.localeCompare(b.name));
  const hash = createHash("sha256").update(JSON.stringify(modules)).digest("hex");
  return Response.json(
    { schemaVersion: 1, hash, generatedAt: new Date().toISOString(), modules },
    { headers: { "Cache-Control": "private, no-store", ETag: `"${hash}"`, "X-Robots-Tag": "noindex" } },
  );
}
